name: Mountain
configs:
  Debug: debug
  Develop: develop
  Staging: staging
  Release: release
options:
  bundleIdPrefix: com.takaoh717
  deploymentTarget:
    iOS: 13.0
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_NAME: $TARGET_NAME
    CURRENT_PROJECT_VERSION: 1
schemes:
  Mountain:
    build:
      targets:
        Mountain: all
        MountainTests: [test]
        MountainUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Develop
    analyze:
      config: Develop
    archive:
      config: Develop
  Mountain-Staging:
    build:
      targets:
        Mountain: all
        MountainTests: [test]
        MountainUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Staging
    analyze:
      config: Debug
    archive:
      config: Staging
  Mountain-Release:
    build:
      targets:
        Mountain: all
        MountainTests: [test]
        MountainUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  Mountain:
    type: application
    platform: iOS
    sources: Mountain
    settings:
      base:
        INFOPLIST_FILE: Mountain/Resources/Info.plist
        CODE_SIGN_STYLE: Manual
        TARGETED_DEVICE_FAMILY: 1
    prebuildScripts:
      - name: Run SwiftGen
        script: make swiftgen
    configs:
      Debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        CODE_SIGN_IDENTITY: iPhone Developer
        DEVELOPMENT_TEAM: J5WW4LM3TV
        PRODUCT_BUNDLE_IDENTIFIER: com.takaoh717.Mountain
        PRODUCT_NAME: $TARGET_NAME
        PROVISIONING_PROFILE_SPECIFIER: Project-profile-debug
      Develop:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVELOP
        CODE_SIGN_IDENTITY: iPhone Distribution
        DEVELOPMENT_TEAM: J5WW4LM3TV
        PRODUCT_BUNDLE_IDENTIFIER: com.takaoh717.Mountain
        PRODUCT_NAME: $TARGET_NAME
        PROVISIONING_PROFILE_SPECIFIER: Project-profile-develop
      Staging:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGING
        CODE_SIGN_IDENTITY: iPhone Distribution
        DEVELOPMENT_TEAM: J5WW4LM3TV
        PRODUCT_BUNDLE_IDENTIFIER: com.takaoh717.Mountain
        PRODUCT_NAME: $TARGET_NAME
        PROVISIONING_PROFILE_SPECIFIER: Project-profile-staging
      Release:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
        CODE_SIGN_IDENTITY: iPhone Developer
        PRODUCT_BUNDLE_IDENTIFIER: com.takaoh717.Mountain
        PRODUCT_NAME: $TARGET_NAME
        PROVISIONING_PROFILE_SPECIFIER: Project-profile-release
    scheme:
      gatherCoverageData: true
      testTargets:
        - MountainTests
        - MountainUITests
  MountainTests:
    type: bundle.unit-test
    platform: iOS
    sources: [MountainTests]
    dependencies:
      - target: Mountain
  MountainUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [MountainUITests]
    dependencies:
      - target: Mountain

